x=int(input("Enter a number: "))
y=int(input("Enter another number: "))
summ=x+y
difference=x-y
product=x*y
division=x/y
remainder=x%y
print ("the sum of ", x, " + ", y, " = ", summ)
print ("the difference of ", x, " - ", y, " = ", difference)
print ("the product of ", x, " x ", y, " = ", product)
print ("the division of ", x, " / ", y, " = ", division)
print ("the remainder of ", x, " % ", y, " = ", remainder)
